import './src/App.css';
export { default as Test } from './src/components/test.svelte';
export {default as Leaderboard} from './src/components/TournamentTemplate/Pages/ActiveTournaments/LeaderBorad.svelte';
export {default as OverView} from './src/components/TournamentTemplate/Pages/ActiveTournaments/OverView.svelte';
export {default as Support} from './src/components/TournamentTemplate/Pages/ActiveTournaments/Support.svelte';
export {default as Videos} from './src/components/TournamentTemplate/Pages/ActiveTournaments/Videos.svelte';
export {default as ComingSoonBanner} from './src/components/ComingsoonBanner.svelte';
export {default as Devider} from './src/components/Devider.svelte';
export {default as Format} from './src/components/Format.svelte';
export {default as General} from './src/components/General.svelte';
export {default as RegisterNowSection} from './src/components/RegisterNowSection.svelte';
export {default as Breadcrumb} from './src/components/Breadcrumb.svelte';
export {default as NavTavb} from './src/components/NavTabs/NavTab.svelte';
export {default as Tablink} from './src//components/NavTabs/TabLink.svelte';
export {default as BannerSection} from './src/components/Sliders/BannerSection.svelte';
export {default as CardSlider} from './src/components/Sliders/CardSlider.svelte';
export {default as HightlightsSlider} from './src/components/Sliders/HighlightsSlider.svelte';
export {default as MediaSlider} from './src/components/Sliders/MediaSlider.svelte';
export {default as InfoSectionKIT} from './src/components/InfoSectionKIT.svelte';
