 
let  createVendor =  {
 
      status: '',
      firstName: '',
      lastName: '',
      designation: '',
      companyName: '',
      dateOfBirth: new Date(),
      companyMarketName: '',
      companyBio: '',
      companyEmail: '',
      companyPhone: '',
      website: '',
      email: '',
      phone: '',
      country: '',
      state: '',
      city: '',
      countryId: '',
      stateId: '',
      cityId: '',
      address: '',
      totalTurnover: '',
      operationalStaffCount: 0,
      contentStaffCount: 0,
      designStaffCount: 0,
      productionStaffCount: 0,
      otherStaffCount: 0,
      categoryA: 0,
      categoryB: 0,
      categoryC: 0,
      tournaments: [],
      legalInformation: {
        legalName: '',
        entityType: '',
        pan: '',
        gst: '',
        incorporationDate: new Date(),
        country: '',
        state: '',
        city: ''
      }
    };